backend:
  name: git-gateway
  branch: main

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "news"
    label: "Mzansi News"
    folder: "content/news"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "motivation"
    label: "Motivation"
    folder: "content/motivation"
    create: true
    fields:
      - { label: "Quote", name: "quote", widget: "string" }

  - name: "videos"
    label: "Videos"
    folder: "content/videos"
    create: true
    fields:
      - { label: "Video Link", name: "link", widget: "string" }
